name: Auto Update README

on:
  push:
    paths:
      - "data/cards.json"
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
      timezone: Asia/Shanghai

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Generate README
        run: |
          pip install urllib3
          python scripts/generate_readme.py
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M')"
          git push origin main
